enablePrePostScripts: false

optimisticRepeatInstall: true

strictDepBuilds: true

minimumReleaseAgeExclude:
  - "@rspack/*"
  - "@rsbuild/*"

  - typescript
  - '@typescript/*'
allowBuilds:
  core-js: false
  dprint: true
