enableGlobalVirtualStore: true

enablePrePostScripts: false

optimisticRepeatInstall: true

strictDepBuilds: true

minimumReleaseAgeExclude:
  - "@rspack/*"
  - "@rsbuild/*"

allowBuilds:
  core-js: false
  dprint: true
